//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteBrite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiteBrite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string menu_about {
            get {
                return ResourceManager.GetString("menu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string menu_exit {
            get {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string menu_file {
            get {
                return ResourceManager.GetString("menu_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Game.
        /// </summary>
        public static string menu_game {
            get {
                return ResourceManager.GetString("menu_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Light.
        /// </summary>
        public static string menu_light {
            get {
                return ResourceManager.GetString("menu_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Light Up.
        /// </summary>
        public static string menu_lightup {
            get {
                return ResourceManager.GetString("menu_lightup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string menu_new {
            get {
                return ResourceManager.GetString("menu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Normal.
        /// </summary>
        public static string menu_normal {
            get {
                return ResourceManager.GetString("menu_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string menu_open {
            get {
                return ResourceManager.GetString("menu_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Random.
        /// </summary>
        public static string menu_random {
            get {
                return ResourceManager.GetString("menu_random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string menu_save {
            get {
                return ResourceManager.GetString("menu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string msgbox_caption_about {
            get {
                return ResourceManager.GetString("msgbox_caption_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string msgbox_caption_notice {
            get {
                return ResourceManager.GetString("msgbox_caption_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any unsaved changes will be discard by this operation.
        /// </summary>
        public static string msgbox_closenotice {
            get {
                return ResourceManager.GetString("msgbox_closenotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your work before starting a new one?.
        /// </summary>
        public static string msgbox_newgamenotice {
            get {
                return ResourceManager.GetString("msgbox_newgamenotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lite Brite - April 2019.
        /// </summary>
        public static string statusbar_text {
            get {
                return ResourceManager.GetString("statusbar_text", resourceCulture);
            }
        }
    }
}
